name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y vault

      - name: Authenticate with Vault
        run: |
          export VAULT_ADDR='http://127.0.0.1:8200'
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          echo "Authenticated with Vault"

      - name: Retrieve secret from Vault
        run: |
          export USERNAME=$(vault kv get -field=username secret/mysecret)
          export PASSWORD=$(vault kv get -field=password secret/mysecret)
          echo "Using username $USERNAME"

