name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: List files to ensure package.json exists
        run: |
          ls -la

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}
          project: ${{ secrets.DOPPLER_PROJECT }}


      - name: Install dependencies
        run: |
          npm install


      - name: Build the app
        run: |
          npm run build

      - name: Deploy the app
        run: |
          npm run deploy
