name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        run: |
          curl -sSL https://cli.doppler.com/install.sh | bash

      - name: Authenticate with Doppler
        run: |
          doppler login --token ${{ secrets.DOPPLER_TOKEN }} 

      - name: Fetch secrets from Doppler
        run: |
          API_KEY=$(doppler secrets get API_KEY --plain)
          DATABASE_PASSWORD=$(doppler secrets get DATABASE_PASSWORD --plain)
          
          echo "Using API Key: $API_KEY"

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build the app
        run: |
          npm run build

      - name: Deploy the app
        run: |
          npm run deploy
