name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Authenticate with Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: doppler setup --token $DOPPLER_TOKEN --no-prompt



      - name: Retrieve secret from Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          echo "Fetching secrets..."
          USE=$(doppler secrets get USE --plain)
          PAROL=$(doppler secrets get PAROL --plain)
          
          echo "$USE"
          echo "$PAROL"