name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files to ensure package.json exists
        run: |
          ls -la

      - name: Set up Doppler CLI
        uses: dopplerhq/action@v3
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}
          project: ${{ secrets.DOPPLER_PROJECT }}
          config: ${{ secrets.DOPPLER_CONFIG }}

      - name: Install dependencies
        run: |
          cd lab3star
          npm install

      - name: Run tests
        run: |
          cd lab3star
          npm test

      - name: Build the app
        run: |
          cd lab3star
          npm run build

      - name: Deploy the app
        run: |
          cd lab3star
          npm run deploy
