name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}  
          project: ${{ secrets.DOPPLER_PROJECT }}  


      - name: Fetch secrets from Doppler
        run: |
         API_KEY=$(doppler secrets get API_KEY --plain)
         DATEBASE_PASSWORD=$(doppler secrets get DATABASE_PASSWORD --plain)
    
         echo "Using API Key: $API_KEY"

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build the app
        run: |
          npm run build

      - name: Deploy the app
        run: |
          npm run deploy
